[package]
name = "htmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
leptos = "0.4.2"
libsql-client = "0.31.8"
serde = "1.0.171"
stylers = "0.3.1"
